name: Lock closed inactive issues

on:
  schedule:
    # Run at 16:00 every day
    - cron: '0 16 * * *'

jobs:
  lock_closed:
    if: github.repository == 'angular/angular'
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@4ec476f45fb1a76cc993b0ee21297ce1eac36194
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
